name: ecms-distribution
recipe: drupal10

config:
  php: "8.1"
  webroot: docroot
  database: mariadb:10.3
  config:
    php: '.lando/php.ini'
  xdebug: false

events:
  # Clear cache after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cache-rebuild --yes

services:
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install

  nodejs:
    type: node:10
    globals:
      gulp-cli: latest
    run:
      - cd $LANDO_MOUNT && npm install
      - cd $LANDO_MOUNT && gulp build

tooling:
  gulp:
    service: nodejs
  node:
    service: nodejs
  npm:
    service: nodejs
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
  security-check:
    service: appserver
    cmd: "php vendor/sensiolabs/security-checker/security-checker security:check composer.lock"
  # Acquia Site Factory commands
  acsf-init:
    service: appserver
    cmd: "cd $LANDO_MOUNT && /app/vendor/bin/drush --include=/app/docroot/modules/contrib/acsf/acsf_init acsf-init --yes"
  acsf-verify:
    service: appserver
    cmd: "cd $LANDO_MOUNT && /app/vendor/bin/drush --include=/app/docroot/modules/contrib/acsf/acsf_init acsf-init-verify"

  # Xdebug toggle switches.
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
