# Builds Drupal and pushes all branches to Acquia.
---
name: Build and Deploy
on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc'

jobs:
  build:
    uses: oomphinc/oomphcloud/.github/workflows/build-drupal.yml@main
    with:
      node-version: '10.x'
      test-drupal: false
      # For testing, remove once dev/non-dev dependencies are fixed
      npm-ci-build-options: '--no-fund --no-progress'
      install-gulp: true
      drupal-archive-contents: 'config vendor docroot composer.json composer.lock hooks'

  deploy:
    needs: build
    uses: oomphinc/oomphcloud/.github/workflows/deploy-drupal-acquia.yml@main
    with:
      acquia-repo-hostname: 'svn-21939.prod.hosting.acquia.com'
      acquia-repo-name: 'risd.git'
      acquia-repo-username: 'risd'
      # Deploy main branch as 'master' and feature branches for use in other environments
      acquia-target-branch: ${{ github.ref_name == 'main' && 'master' || github.ref_name }}
    secrets:
      acquia-repo-private-key: ${{ secrets.ACQUIA_SSH_KEY }}
